version: '3.1'

services:

  knight_redis:
    restart: always
    build: ./redis/
    ports:
      - "16379:6379"
    volumes:
      - /opt/knight/knight/redis_data:/data
    networks:
      - default
      - knight_net

  knight_nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    networks:
      - default
      - knight_net
    depends_on:
      - knight_backend
    volumes:
      - /opt/knight/src/frontend:/usr/share/nginx/html
      - /etc/localtime:/etc/localtime

  knight_mysql:
    restart: always
    build: ./mysql
    ports:
      - "13306:3306"
    env_file:
      - ./env/mysql
      - ./env/app
    networks:
      - default
      - knight_net
    volumes:
      - /opt/knight/data/mysql_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime

  knight_mongo:
    restart: always
    build: ./mongo
    ports:
      - "17017:27017"
    env_file:
      - ./env/mongo
      - ./env/app
    networks:
      - default
      - knight_net
    volumes:
      - /opt/knight/data/mongo_data:/data/db
      - /etc/localtime:/etc/localtime


  knight_emqx:
    restart: always
    build: ./emqx/
    ports:
      - "18083:18083"
      - "13125:1883"
    env_file:
      - ./env/emqx
    networks:
      - default
      - knight_net
    volumes:
      - /etc/localtime:/etc/localtime

  knight_backend:
    image: knight:lastest
    privileged: true
    links:
      - knight_mysql:knight_mysql
      - knight_mongo:knight_mongo
      - knight_redis:knight_redis
      - knight_broadcast:knight_broadcast
      - knight_emqx:knight_emqx

    depends_on:
      - knight_mysql
      - knight_mongo
      - knight_redis
      - knight_broadcast
      - knight_emqx
    networks:
      - default
      - knight_net
    volumes:
      - /opt/knight/src/knightbackend:/yurnero/
      - /var/log/knight/:/var/log/knight/
      - /opt/knight/static_data:/file/
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - /sbin/hwclock:/sbin/hwclock
    env_file:
      - ./env/app
      - ./env/mqtt
    environment:
      DEBUG: 'false'
    command: 'uwsgi --ini /yurnero/uwsgi.ini'
    sysctls:
      net.core.somaxconn: 65535
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  knight_fileserver:
    image: knight:lastest
    privileged: true
    links:
      - knight_mysql:knight_mysql
      - knight_mongo:knight_mongo
      - knight_redis:knight_redis
      - knight_broadcast:knight_broadcast
      - knight_emqx:knight_emqx
    external_links:
      - edtechusercompose_edtechuser_mysql_1:edtechuser_mysql
    depends_on:
      - knight_mysql
      - knight_mongo
      - knight_redis
      - knight_broadcast
      - knight_emqx
    networks:
      - default
      - knight_net
    volumes:
      - /opt/knight/src/knightbackend:/yurnero/
      - /var/log/knight/:/var/log/knight/
      - /opt/knight/static_data:/file/
      - /opt/knight/knight/resource_upgrade:/upgrade/
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - /sbin/hwclock:/sbin/hwclock
    env_file:
      - ./env/app
      - ./env/mqtt
    environment:
      DEBUG: 'false'
    command: 'uwsgi --ini /yurnero/uwsgi.ini'
    sysctls:
      net.core.somaxconn: 65535
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  knight_proxy_nginx:
    restart: always
    build: ./nginx/
    ports:
      - "82:82"
      - "14001:14001"
    links:
      - knight_backend:backend
      - knight_fileserver:fileserver
    networks:
      - default
      - knight_net
    depends_on:
      - knight_backend
      - knight_fileserver
    volumes:
      - /opt/knight/src/knightfrontend:/usr/share/nginx/html
      - /opt/knight/src:/usr/share/nginx
      - /opt/knight/compose/knightcompose/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /opt/knight/compose/knightcompose/nginx/conf.d:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime

networks:
  knight_net:
    external: true
